<?xml version="1.0" encoding="utf-8"?>
<corpus xmlns="http://ufal.mff.cuni.cz/pdt/pml/" id="DEMO">
  <head xmlns:s="http://ufal.mff.cuni.cz/pdt/pml/schema/">
    <schema>
      <s:pml_schema version="1.1">
        <s:revision>0.1</s:revision>
        <s:description>Automatically generated by tiger2pml.xsl</s:description>
        <s:root name="corpus">
          <s:structure>
            <s:member name="id" role="#ID" as_attribute="1">
              <s:cdata format="ID"/>
            </s:member>
            <s:member name="meta" type="tiger-meta.type"/>
            <s:member name="body" type="tiger-body.type"/>
          </s:structure>
        </s:root>
        <s:type name="tiger-meta.type">
          <s:structure>
            <s:member name="name">
              <s:cdata format="any"/>
            </s:member>
            <s:member name="author">
              <s:cdata format="any"/>
            </s:member>
            <s:member name="date">
              <s:cdata format="any"/>
            </s:member>
            <s:member name="description">
              <s:cdata format="any"/>
            </s:member>
            <s:member name="format">
              <s:cdata format="any"/>
            </s:member>
            <s:member name="history">
              <s:cdata format="any"/>
            </s:member>
          </s:structure>
        </s:type>
        <s:type name="tiger-body.type">
          <s:sequence role="#TREES">
            <s:element name="s" type="tiger-sentence.type"/>
          </s:sequence>
        </s:type>
        <s:type name="tiger-sentence.type">
          <s:structure role="#NODE">
            <s:member name="id" role="#ID" as_attribute="1">
              <s:cdata format="ID"/>
            </s:member>
            <s:member name="root" role="#CHILDNODES">
              <s:sequence content_pattern="(t|nt)">
                <s:element name="nt" type="tiger-nt.type"/>
                <s:element name="t" type="tiger-t.type"/>
              </s:sequence>
            </s:member>
          </s:structure>
        </s:type>
        <s:type name="tiger-nt.type">
          <s:structure role="#NODE">
            <s:member name="id" role="#ID" as_attribute="1">
              <s:cdata format="ID"/>
            </s:member>
            <s:member name="label" type="tiger-edgelabel.type"/>
            <s:member name="cat" as_attribute="1">
              <s:choice>
                <s:value>ADJP</s:value>
                <s:value>NP</s:value>
                <s:value>PP</s:value>
                <s:value>S</s:value>
                <s:value>UCP</s:value>
                <s:value>VP</s:value>
              </s:choice>
            </s:member>
            <s:member name="secedges">
              <s:sequence>
                <s:element name="secedge" type="tiger-secedge.type"/>
              </s:sequence>
            </s:member>
            <s:member name="children" role="#CHILDNODES">
              <s:sequence content_pattern="(nt|t)*">
                <s:element name="nt" type="tiger-nt.type"/>
                <s:element name="t" type="tiger-t.type"/>
              </s:sequence>
            </s:member>
          </s:structure>
        </s:type>
        <s:type name="tiger-t.type">
          <s:structure role="#NODE">
            <s:member name="id" role="#ID" as_attribute="1">
              <s:cdata format="ID"/>
            </s:member>
            <s:member name="label" type="tiger-edgelabel.type"/>
            <s:member name="word" as_attribute="1">
              <s:cdata format="any"/>
            </s:member>
            <s:member name="pos" as_attribute="1">
              <s:choice>
                <s:value>,</s:value>
                <s:value>-NONE-</s:value>
                <s:value>.</s:value>
                <s:value>CC</s:value>
                <s:value>CD</s:value>
                <s:value>DT</s:value>
                <s:value>IN</s:value>
                <s:value>JJ</s:value>
                <s:value>MD</s:value>
                <s:value>NN</s:value>
                <s:value>NNP</s:value>
                <s:value>NNS</s:value>
                <s:value>VB</s:value>
                <s:value>VBD</s:value>
                <s:value>VBN</s:value>
              </s:choice>
            </s:member>
            <s:member name="secedges">
              <s:sequence>
                <s:element name="secedge" type="tiger-secedge.type"/>
              </s:sequence>
            </s:member>
          </s:structure>
        </s:type>
        <s:type name="tiger-secedge.type">
          <s:structure>
            <s:member name="idref" required="1" as_attribute="1">
              <s:cdata format="PMLREF"/>
            </s:member>
            <s:member name="label" required="0" as_attribute="1">
              <s:choice>
                <s:value>*</s:value>
              </s:choice>
            </s:member>
          </s:structure>
        </s:type>
        <s:type name="tiger-edgelabel.type">
          <s:choice>
            <s:value>--</s:value>
            <s:value>CLR</s:value>
            <s:value>PRD</s:value>
            <s:value>SBJ</s:value>
            <s:value>TMP</s:value>
          </s:choice>
        </s:type>
      </s:pml_schema>
    </schema>
  </head>
  <meta>
    <name>two sentences of Wall Street Journal corpus</name>
    <format>bracketing format</format>
  </meta>
  <body>
    <s id="s1">
      <root xmlns:s="http://ufal.mff.cuni.cz/pdt/pml/schema/">
        <nt id="s1_500" cat="S">
          <secedges/>
          <children>
            <nt id="s1_501" cat="NP">
              <label>SBJ</label>
              <secedges/>
              <children>
                <nt id="s1_502" cat="NP">
                  <label>--</label>
                  <secedges/>
                  <children>
                    <t id="s1_1" word="Pierre" pos="NNP">
                      <label>--</label>
                      <secedges/>
                    </t>
                    <t id="s1_2" word="Vinken" pos="NNP">
                      <label>--</label>
                      <secedges/>
                    </t>
                  </children>
                </nt>
                <t id="s1_3" word="," pos=",">
                  <label>--</label>
                  <secedges/>
                </t>
                <nt id="s1_503" cat="ADJP">
                  <label>--</label>
                  <secedges/>
                  <children>
                    <nt id="s1_504" cat="NP">
                      <label>--</label>
                      <secedges/>
                      <children>
                        <t id="s1_4" word="61" pos="CD">
                          <label>--</label>
                          <secedges/>
                        </t>
                        <t id="s1_5" word="years" pos="NNS">
                          <label>--</label>
                          <secedges/>
                        </t>
                      </children>
                    </nt>
                    <t id="s1_6" word="old" pos="JJ">
                      <label>--</label>
                      <secedges/>
                    </t>
                  </children>
                </nt>
                <t id="s1_7" word="," pos=",">
                  <label>--</label>
                  <secedges/>
                </t>
              </children>
            </nt>
            <nt id="s1_505" cat="VP">
              <label>--</label>
              <secedges/>
              <children>
                <t id="s1_8" word="will" pos="MD">
                  <label>--</label>
                  <secedges/>
                </t>
                <nt id="s1_506" cat="VP">
                  <label>--</label>
                  <secedges/>
                  <children>
                    <t id="s1_9" word="join" pos="VB">
                      <label>--</label>
                      <secedges/>
                    </t>
                    <nt id="s1_507" cat="NP">
                      <label>--</label>
                      <secedges/>
                      <children>
                        <t id="s1_10" word="the" pos="DT">
                          <label>--</label>
                          <secedges/>
                        </t>
                        <t id="s1_11" word="board" pos="NN">
                          <label>--</label>
                          <secedges/>
                        </t>
                      </children>
                    </nt>
                    <nt id="s1_508" cat="PP">
                      <label>CLR</label>
                      <secedges/>
                      <children>
                        <t id="s1_12" word="as" pos="IN">
                          <label>--</label>
                          <secedges/>
                        </t>
                        <nt id="s1_509" cat="NP">
                          <label>--</label>
                          <secedges/>
                          <children>
                            <t id="s1_13" word="a" pos="DT">
                              <label>--</label>
                              <secedges/>
                            </t>
                            <t id="s1_14" word="nonexecutive" pos="JJ">
                              <label>--</label>
                              <secedges/>
                            </t>
                            <t id="s1_15" word="director" pos="NN">
                              <label>--</label>
                              <secedges/>
                            </t>
                          </children>
                        </nt>
                      </children>
                    </nt>
                    <nt id="s1_510" cat="NP">
                      <label>TMP</label>
                      <secedges/>
                      <children>
                        <t id="s1_16" word="Nov." pos="NNP">
                          <label>--</label>
                          <secedges/>
                        </t>
                        <t id="s1_17" word="29" pos="CD">
                          <label>--</label>
                          <secedges/>
                        </t>
                      </children>
                    </nt>
                  </children>
                </nt>
              </children>
            </nt>
            <t id="s1_18" word="." pos=".">
              <label>--</label>
              <secedges/>
            </t>
          </children>
        </nt>
      </root>
    </s>
    <s id="s3">
      <root xmlns:s="http://ufal.mff.cuni.cz/pdt/pml/schema/">
        <nt id="s3_500" cat="S">
          <secedges/>
          <children>
            <nt id="s3_501" cat="NP">
              <label>SBJ</label>
              <secedges>
                <secedge label="*" idref="s3_18"/>
              </secedges>
              <children>
                <nt id="s3_502" cat="NP">
                  <label>--</label>
                  <secedges/>
                  <children>
                    <t id="s3_1" word="Rudolph" pos="NNP">
                      <label>--</label>
                      <secedges/>
                    </t>
                    <t id="s3_2" word="Agnew" pos="NNP">
                      <label>--</label>
                      <secedges/>
                    </t>
                  </children>
                </nt>
                <t id="s3_3" word="," pos=",">
                  <label>--</label>
                  <secedges/>
                </t>
                <nt id="s3_503" cat="UCP">
                  <label>--</label>
                  <secedges/>
                  <children>
                    <nt id="s3_504" cat="ADJP">
                      <label>--</label>
                      <secedges/>
                      <children>
                        <nt id="s3_505" cat="NP">
                          <label>--</label>
                          <secedges/>
                          <children>
                            <t id="s3_4" word="55" pos="CD">
                              <label>--</label>
                              <secedges/>
                            </t>
                            <t id="s3_5" word="years" pos="NNS">
                              <label>--</label>
                              <secedges/>
                            </t>
                          </children>
                        </nt>
                        <t id="s3_6" word="old" pos="JJ">
                          <label>--</label>
                          <secedges/>
                        </t>
                      </children>
                    </nt>
                    <t id="s3_7" word="and" pos="CC">
                      <label>--</label>
                      <secedges/>
                    </t>
                    <nt id="s3_506" cat="NP">
                      <label>--</label>
                      <secedges/>
                      <children>
                        <nt id="s3_507" cat="NP">
                          <label>--</label>
                          <secedges/>
                          <children>
                            <t id="s3_8" word="former" pos="JJ">
                              <label>--</label>
                              <secedges/>
                            </t>
                            <t id="s3_9" word="chairman" pos="NN">
                              <label>--</label>
                              <secedges/>
                            </t>
                          </children>
                        </nt>
                        <nt id="s3_508" cat="PP">
                          <label>--</label>
                          <secedges/>
                          <children>
                            <t id="s3_10" word="of" pos="IN">
                              <label>--</label>
                              <secedges/>
                            </t>
                            <nt id="s3_509" cat="NP">
                              <label>--</label>
                              <secedges/>
                              <children>
                                <t id="s3_11" word="Consolidated" pos="NNP">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                                <t id="s3_12" word="Gold" pos="NNP">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                                <t id="s3_13" word="Fields" pos="NNP">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                                <t id="s3_14" word="PLC" pos="NNP">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                              </children>
                            </nt>
                          </children>
                        </nt>
                      </children>
                    </nt>
                  </children>
                </nt>
                <t id="s3_15" word="," pos=",">
                  <label>--</label>
                  <secedges/>
                </t>
              </children>
            </nt>
            <nt id="s3_510" cat="VP">
              <label>--</label>
              <secedges/>
              <children>
                <t id="s3_16" word="was" pos="VBD">
                  <label>--</label>
                  <secedges/>
                </t>
                <nt id="s3_511" cat="VP">
                  <label>--</label>
                  <secedges/>
                  <children>
                    <t id="s3_17" word="named" pos="VBN">
                      <label>--</label>
                      <secedges/>
                    </t>
                    <nt id="s3_512" cat="S">
                      <label>--</label>
                      <secedges/>
                      <children>
                        <nt id="s3_513" cat="NP">
                          <label>SBJ</label>
                          <secedges/>
                          <children>
                            <t id="s3_18" word="*" pos="-NONE-">
                              <label>--</label>
                              <secedges/>
                            </t>
                          </children>
                        </nt>
                        <nt id="s3_514" cat="NP">
                          <label>PRD</label>
                          <secedges/>
                          <children>
                            <nt id="s3_515" cat="NP">
                              <label>--</label>
                              <secedges/>
                              <children>
                                <t id="s3_19" word="a" pos="DT">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                                <t id="s3_20" word="nonexecutive" pos="JJ">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                                <t id="s3_21" word="director" pos="NN">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                              </children>
                            </nt>
                            <nt id="s3_516" cat="PP">
                              <label>--</label>
                              <secedges/>
                              <children>
                                <t id="s3_22" word="of" pos="IN">
                                  <label>--</label>
                                  <secedges/>
                                </t>
                                <nt id="s3_517" cat="NP">
                                  <label>--</label>
                                  <secedges/>
                                  <children>
                                    <t id="s3_23" word="this" pos="DT">
                                      <label>--</label>
                                      <secedges/>
                                    </t>
                                    <t id="s3_24" word="British" pos="JJ">
                                      <label>--</label>
                                      <secedges/>
                                    </t>
                                    <t id="s3_25" word="industrial" pos="JJ">
                                      <label>--</label>
                                      <secedges/>
                                    </t>
                                    <t id="s3_26" word="conglomerate" pos="NN">
                                      <label>--</label>
                                      <secedges/>
                                    </t>
                                  </children>
                                </nt>
                              </children>
                            </nt>
                          </children>
                        </nt>
                      </children>
                    </nt>
                  </children>
                </nt>
              </children>
            </nt>
            <t id="s3_27" word="." pos=".">
              <label>--</label>
              <secedges/>
            </t>
          </children>
        </nt>
      </root>
    </s>
  </body>
</corpus>
