#!/usr/bin/perl
#                                                          -*- cperl -*-
if ($^V lt v5.6.0) {
  print STDERR '-' x 50,"\n";
  print STDERR "WARNING: Your version of perl is older than v5.6.0\n";
  print STDERR "THINGS MAY NOT WORK AS EXPECTED!\n";
  print STDERR '-' x 50,"\n\n";
}

use Getopt::Std;
getopts('p:r:s:a:f:x:CETADRNGhu');

if (@ARGV<1 or $opt_h or $opt_u) {
  print <<EOF;
Usage: any2any [-s strip-sfx] [-a append-sfx] [-p strip-prefix]
               [-r add-prefix] [-f out-fmt] [-x extra_attribs]
               [ flags ] file1 [ file2 ... ]
EOF

  if ($opt_h) {
    print <<EOF;
Open a file and save it in FS format
Parameters:
  -f format          output format; one of: fs, csts, trxml, teixml. Default is csts.
  -s suffix_regexp   strip strings matching given regexp from the end of filenames
  -a append          append given suffix to the filenames
  -p prefix_regexp   remove strings matching given regexp from the beginning of filenames
  -r prepend         prepend filenames with the given prefix
  -x extra_attribs   comma separated list of non-CSTS attributes to preserve when
                     converting to CSTS

  -T                 if converting from csts, build tectogrammatical tree structure
  -A                 when converting from csts, use header for Arabic PADT treebank
  -R                 same as -T (for compatibility with TrEd/bTrEd)
  -N                 if empty, initialize ordering attribute with sentence ordering
  -G                 do not save dependency on the root of the tree in csts format
  -C                 convert to CSTS in mode quite compatible with Dan Zemans cstsfs
  -E                 convert to CSTS save err1 attribute to (non-CSTS) <err> element
  -D                 print some debugging information
EOF
  }
  exit 0;
}

use FindBin;
my $rb=$FindBin::RealBin;
if (exists $ENV{TREDHOME}) {
  $libDir=$ENV{TREDHOME};
} elsif (-d "$rb/tredlib") {
  $libDir="$rb/tredlib";
} elsif (-d "$rb/../lib/tredlib") {
  $libDir="$rb/../lib/tredlib";
} elsif (-d "$rb/../lib/tred") {
  $libDir="$rb/../lib/tred";
}
print STDERR "Trying $libDir\n" if ($libDir);
unshift @INC,"$libDir";

require Fslib;
import Fslib;

#require CSTS_SGML_SP_Backend;
@backends=('FSBackend',ImportBackends(qw(AG2FS TrXMLBackend TEIXMLBackend CSTS_SGML_SP_Backend)));

$CSTS_SGML_SP_Backend::doctype = "$libDir/csts.doctype";

($opt_T || $opt_R) && Csts2fs::setupTR();
$opt_A && Csts2fs::setupPADTAR();

@Fs2csts::extra_attributes=split /,/,$opt_x;

$Fslib::Debug=1 if $opt_D;
$Csts2fs::fill_empty_ord = 1 if $opt_N;
$Fs2csts::export_dependency = 0 if $opt_G;
$Fs2csts::compatibility_mode = 1 if $opt_C;
$Fs2csts::preserve_err1 = 1 if $opt_E;

our $inputenc='iso-8859-2';

%bkmap=(
	fs => 'FSBackend',
	csts => 'CSTS_SGML_SP_Backend',
	trxml => 'TrXMLBackend',
	teixml => 'TEIXMLBackend'
);

$fileno=0;

my @files;
if ($^O eq 'MSWin32') {
  @files=map glob, @ARGV;
} else {
  @files = @ARGV;
}
$filecount=scalar(@files);

$format=defined($opt_f) ? lc($opt_f) : "csts";
unless (  $backend = $bkmap{$format} ) {
  die "Unknown format $format. Use -f [fs|csts|trxml|teixml]\n";
}

foreach $f (@files) {
  $fileno++;

  my $out=$f;

  my $eval;
  $eval.="s%$opt_s\$%%;"  if ($opt_s);
  $eval.="\$_.=\"$opt_a\";" if ($opt_a);
  $eval.="s%^$opt_p%%;" if ($opt_p);
  $eval.="\$_=\"$opt_r\".\$_;" if ($opt_r);
  if ($eval) {
    use Safe;
    my $compartment = new Safe;
    $compartment->permit_only(qw(concat :base_core));
    $_=$out;
    $compartment->reval($eval);
    print STDERR $@ if $@;
    $out=$_;
  }

  print STDERR "$f\t->\t$out\t",int(100*$fileno / $filecount),"%\t$fileno of $filecount\n";
  $fs = FSFile->newFSFile($f,$inputenc,@backends);
  if ($fs->lastTreeNo<0) {
    print STDERR "$f: empty or corrupt file!\n";
    next;
  }
  $fs->changeBackend($backend);

  if ($f eq $out) {
    unlink "$f~" if (-e "$f~" ); # silly MS OSs need this
    rename $f, "$f~" || die "Cannot create backup file named $f~ for $f\n";
  }

#   if ($opt_T || $opt_R) {
#     $fs->changePatterns('${trlemma}<? ".#{custom1}\${aspect}" if $${aspect} =~/PROC|CPL|RES/ ?>',
#                     '<?$${funcaux} if $${funcaux}=~/\#/?>${func}<? "_#{custom2}\${reltype}\${memberof}" if "$${memberof}$${reltype}" =~ /CO|AP|PA/ ?><? ".#{custom3}\${gram}" if $${gram} ne "???" and $${gram} ne ""?>');
#     $fs->changeHint('<?"fw:\t\${fw}\n" if $${fw} ne "" ?>form:'."\t".'${form}'."\n".
# 		      "afun:\t\${afun}\ntag:\t\${tag}".
# 		      '<?"\ncommentA:\t\${commentA}\n" if $${commentA} ne "" ?>');
#   }

  $fs->writeFile($out);
  undef $fs;
}
