name: CI

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
  matrix-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
            - "5.26.0"
            - "5.34.0"
            - "5.40.1"
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - uses: actions/checkout@v4
      - name: Regular tests
        run: |
          tred_refactored/deve/unix_install/packages_unix/install
          prove -vl t
