#!/usr/bin/perl
BEGIN {
  use File::Basename;
  use lib dirname($0).'/../tredlib';
  use Fslib;
  use PMLInstance;
};

my $filename = 'test.t';
my $a_file;
if (@ARGV>1) {
  die "Usage: $0 [a-file]\n";
} elsif (@ARGV) {
  $a_file = shift;
  print STDERR "Assuming a-file: $a_file\n";
} else {
  print STDERR "No a-file: use $0 <a-filename>\n";
}

# where to look for PML schemata?
Fslib::AddResourcePath(dirname($0).'/../resources');

my $aref = defined $a_file ?
  qq(<reffile id="a" href="$a_file" name="adata"/>) : q();
my $pml = <<"EOF";
<?xml version="1.0" encoding="utf-8"?>
<tdata xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="tdata_schema.xml"/>
  <references>
   $aref
   <reffile id="v" href="vallex.xml" name="vallex"/>
  </references>
 </head>
 <meta>
  <annotation_info>
   <desc>Automatically generated by PML_A2T.mak</desc>
  </annotation_info>
 </meta>
 <trees/>
</tdata>
EOF

my $fsfile = PMLInstance->load({
  string   => $pml,
  filename => $filename,
})->convert_to_fsfile();

# create 10 sample trees
my ($root,$node);
foreach my $i (1..10) {
  $root=$fsfile->new_tree($i-1);	# create a new root
  $root->{id}="tree.$i";
  $root->{nodetype}="root";
  $root->{deepord}=0;
  foreach my $j (1..4) {
    $node=FSNode->new();	# create a new node
    $node->{id}="node-$i.$j";
    $node->{nodetype}="complex";
    $node->{t_lemma}="$j";
    $node->{functor}="RSTR";
    $node->{deepord}=$j;
    Fslib::Paste($node,$root,$fsfile->FS); # paste the node on root
  }
}

print STDERR "Saving $filename\n";
$fsfile->writeFile();
