#!/bin/sh

for s in tred.def Fslib.pm PMLSchema.pm PMLInstance.pm; do
  d=${s/.def/_def}
  pod2xml tredlib/$s | xsltproc devel/pod2db.xsl - \
   | devel/pod2db.xsh -P- > documentation/manual/${d%.*}.xml
done

cd documentation
xsltproc --xinclude --stringparam html.stylesheet blue.css --stringparam root.filename tred manual/manual.xsl manual/tred.xml
xsltproc -o bn-tutorial.html --xinclude --stringparam html.stylesheet blue.css manual/manual_one_page.xsl bn-tutorial.xml
