#!/bin/sh

if [ ! -f documentation/manual/tred.xml ]; then
  echo "not in tred/ directory"
  exit 1
fi

echo "Generating documentation from tred.def"
pod2xml tredlib/tred.def | xsltproc devel/pod2db.xsl - \
    | devel/pod2db.xsh -q -P- > documentation/manual/tred_def.xml

DEVELDIR=`dirname $0`
DEVELDIR="${DEVELDIR:-$PWD}"
pushd "$DEVELDIR" >/dev/null
DEVELDIR=`pwd -P`
popd >/dev/null

echo "Generating documentation from POD"
"$DEVELDIR"/make_pod_html documentation

cd documentation
[ -d man ] || mkdir man
for man in btred.1 ntred.1 Fslib.3 \
           PMLSchema.3 PMLInstance.3 PML_mak.3 tred_def.3
do
  pod2man "pod/${man%.[13]}.pod" > "man/$man"
done

RUNXSLT="xsltproc --xinclude --stringparam html.stylesheet blue.css"

echo "Generating TrEd manual"
$RUNXSLT --stringparam root.filename tred manual/manual.xsl manual/tred.xml

echo "Generating on-line help map"
xsh2 ../devel/make_help_map.xsh manual/tred.xml ar*.html > ../tredlib/TrEd/Help.pm

echo "Generating bTrEd tutorial"
$RUNXSLT -o bn-tutorial.html manual/manual_one_page.xsl bn-tutorial.xml
RW_MAP="$DEVELDIR"/rewrite_tred.xml rewrite -q bn-tutorial.html
$RUNXSLT -o btred-tutorial.html manual/manual_one_page.xsl btred_tutorial.xml

rm -f *.html~

echo "done."
