#!/bin/bash

function suply_answers() {
	echo 'yes'
	echo 'sudo'
	echo 'yes'
	echo 'yes'
	echo 'yes'
	echo 'yes'
	echo 'yes'
	echo 'yes'
	echo 'yes'
	echo 'yes'
}


# Install remaining CPAN packages
#suply_answers | perl -MCPAN -e 'install "UNIVERSAL::DOES", "XML::CompactTree", "XML::CompactTree::XS", "Treex::PML"'
cpanm --sudo --no-interactive UNIVERSAL::DOES XML::CompactTree XML::CompactTree::XS Treex::PML
